# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "cryptd" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d3b9a6a8-e8bf-40fc-8633-13563aa36560";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-bcb527cd-e870-464c-afef-db3f17bc580a".device = "/dev/disk/by-uuid/bcb527cd-e870-464c-afef-db3f17bc580a";
  boot.initrd.luks.devices."luks-a7fdb996-0a2b-4fea-b417-c71d8474b116".device = "/dev/disk/by-uuid/a7fdb996-0a2b-4fea-b417-c71d8474b116";
  boot.initrd.luks.reusePassphrases = true;

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EE9A-B919";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c18af33d-4c64-4672-a1f1-b6b794bb29db"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
